apiVersion: v1
kind: Service
metadata:
  name: fellowship-api-service
spec:
  type: LoadBalancer
  selector:
    app: fellowship-api
  ports:
    - protocol: TCP
      port: 80          # The port exposed externally
      targetPort: 8000  # The port your FastAPI app runs on internally
