apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9uZWVsX3VzZXI6dHJhY2tlciU0MFBCMjZAY2x1c3RlcjAueWljb2J6aC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  SERPER_API_KEY: MjhhNjdkYWViMGYyMTkzMjU1ZDcyNDUxY2E5ZWE0N2U0OWY2ZGU0Zg==
  GROQ_API_KEY: Z3NrX1V2WFdTRlJkUm9zNmJ5Mk9xaHNGV0dkeWIzRllIcVR6VHhDQWZVbDhCVWp5MkhWTmd3Tm0=
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvd2ViaG9va3MvMTQ3ODQ0MDkwMzk4MTkyODU2OC8tVEgxZEJkcm05OFdaaVVEYmxuV2o1a0VXOFZodDN3dHpiSnZHMWlLQkp6SUdVZXJCT2NSM05EakpVeDV2aFZSWW56Zw==
